version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - /home/justin/2024:/home/jovyan/work/2024
    ports:
      - 9999:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
