# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."jupyter_notebook" = {
    image = "localhost/compose2nix/jupyter_notebook";
    volumes = [
      "/home/justin/2024:/home/jovyan/work/2024:rw"
      "/home/justin/2025/jupyter-docker-compose-with-nix/dot-jupyter:/home/jovyan/.juypter:rw"
      "/home/justin/2025/jupyter-docker-compose-with-nix/work:/home/jovyan/work:rw"
    ];
    ports = [
      "9999:8888/tcp"
    ];
    cmd = [ "start-notebook.sh" "--NotebookApp.token=" ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=jupyter"
      "--network=jupyter_default"
      "--privileged"
    ];
  };
  systemd.services."podman-jupyter_notebook" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-jupyter_default.service"
    ];
    requires = [
      "podman-network-jupyter_default.service"
    ];
    partOf = [
      "podman-compose-jupyter-root.target"
    ];
    wantedBy = [
      "podman-compose-jupyter-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-jupyter_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f jupyter_default";
    };
    script = ''
      podman network inspect jupyter_default || podman network create jupyter_default
    '';
    partOf = [ "podman-compose-jupyter-root.target" ];
    wantedBy = [ "podman-compose-jupyter-root.target" ];
  };

  # Builds
  systemd.services."podman-build-jupyter_notebook" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/justin/2025/jupyter-docker-compose-with-nix
      podman build -t compose2nix/jupyter_notebook -f ./docker/jupyter/Dockerfile .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-jupyter-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
