version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - ./dot-jupyter:/home/jovyan/.juypter # persistent settings
      - /home/justin/2024:/home/jovyan/work/2024
    ports:
      - 9999:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
